project:
  type: website
  output-dir: docs

website:
  title: "LDS Hymn Stats"
  description: "Trends, patterns, stats, and trivia about LDS hymns. Based on data collected from over 25,000 sacrament meetings."
  site-url: https://hymnstats.joeystanley.com
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: findings.qmd
        text: "Blog"
      - href: overview.qmd
        text: "Summarized Data"
      - href: contribute.qmd
      - href: about.qmd
    right:
      - icon: twitter
        href: https://twitter.com/ldshymnstats
      - icon: github
        href: https://github.com/JoeyStanley/lds-hymn-stats
      - icon: rss 
        href: findings.xml
  margin-header: |
    ![](/images/logo.jpeg)
  page-footer: 
    center: "Copyright 2024, Joey Stanley" 
    border: true
    background: light
  twitter-card: true
  open-graph: true
  reader-mode: true
  google-analytics: "G-SG4E42NZ2F"
    
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: source

resources:
  - CNAME

execute:
  freeze: true