project:
  type: website
  output-dir: docs

website:
  title: "LDS Hymn Stats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: findings.qmd
      - href: contribute.qmd
      - href: about.qmd
    right:
      - icon: twitter
        href: https://twitter.com/ldshymnstats
      - icon: github
        href: https://github.com/JoeyStanley/lds-hymn-stats
  margin-header: |
    ![](/images/logo.jpeg)
  page-footer: 
    center: "Copyright 2023, Joey Stanley" 
    border: true
    background: light
  twitter-card: true
  open-graph: true
  reader-mode: true
  google-analytics: "G-SG4E42NZ2F"
    
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

