project:
  type: website
  output-dir: docs

website:
  title: "LDS Hymn Stats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: findings.qmd
      - href: contribute.qmd
      - href: about.qmd
  margin-header: |
    ![](/images/logo.jpeg)
  twitter-card: true
  open-graph: true
  google-analytics: "G-SG4E42NZ2F"
    
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

