project:
  type: website

website:
  title: "LDS Hymn Stats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: contribute.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

