---
title: "About Me"
---

My name is Joey Stanley and I've been working on this project since 2013. It started with one simple question: "What is the most common hymn?" Initially, I sought to answer this question by collecting a year's worth of data from 1000 wards across the country. A pipe dream if there ever was one. But I have been able to get enough data to the point where I believe I've hit a critical mass. It's more than a lifetime's worth of sacrament meetings for any one person (even if you attend multiple sacrament meetings for a few decades), and enough to uncover some pretty subtle patterns.

I am a [linguistics professor at BYU](https://ling.byu.edu/meet-dr-stanley), which means I am not a statistician or musicologist, though I do have some training in both statistics and music. What qualifies me for this project are my skills in data analysis and vizualization, as well as my sheer interest in the project.

I'm motivated to complete this project soon because the church will soon release a new hymnal, at which point all of my data will be obsolete. I hope that I can get these results out there so that people can use it help them with their callings, so the church can use it when designing the new hymnal, and to provide a snapshot of hymn usage data before the 1985 hymnal is phased out.

I've been primary pianist twice and sacrament accompanist twice, but not for too long because I find myself getting called to other positions. Ironically, I've never been a music coordinator, so I've never had the responsibility of choosing sacrament hymns!
