---
title: "Contribute"
---

Click below depending on how much data you have to contribute.

::: {.panel-tabset}

## Submit many weeks' worth of data

Here are the best ways you can help out:

1.  Someone in your ward likely keeps a spreadsheet that has the past few weeks/months/years of hymns sung in sacrament meeting in your ward. This is typically shared between the music coordinator, chorister(s), organist(s), and a bishopric member. If you or someone close to you has access to that spreadsheet, you can simply send a copy to me. This is probably the best way to contribute to this project.

2.  If you have a collection of old sacrament meeting programs from your ward, either digital or physical, those usually list the hymns that were sung that week. (I know hardly anyone carries physical scriptures anymore, but look through those to see if there are any old ones tucked away in there!) You can either write down the information from those programs onto a new spreadsheet or document and send me that, or just send me copies of the programs themselves.

3.  Return to this page and submit the form every week.

It doesn't matter if the sacrament meeting info you send me is recent or not. One ward sent me information from 2003! It also doesn't matter if there are gaps in your contribution. So if you have data from 2018 and then more from 2023 but missed the years in between, that's totally fine!

If you contribute at least year's worth of sacrament meetings, I'll be able to run some stats on your ward, like how varied your hymns are or how unusual they are, compared to other wards. But, any amount of data helps---even if it's just from a single week or two!

Again, email whatever contributions you have to [hymnstats\@gmail.com](mailto:hymnstats@gmail.com) and I'll incorporate it into the analysis as quickly as I can!

## Submit one week's worth of data

<iframe src="https://byu.az1.qualtrics.com/jfe/form/SV_bgx0RRttJ7r7ymy" height="1800px" width="800px"></iframe>


:::

