<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Joey Stanley">
<meta name="dcterms.date" content="2023-09-19">

<title>LDS Hymn Stats - Does anyone sing the women’s and men’s arrangements?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-SG4E42NZ2F"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-SG4E42NZ2F', { 'anonymize_ip': true});
</script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="LDS Hymn Stats - Does anyone sing the women’s and men’s arrangements?">
<meta property="og:description" content="">
<meta property="og:image" content="https://hymnstats.joeystanley.com/images/womens_mens.jpeg">
<meta property="og:site-name" content="LDS Hymn Stats">
<meta name="twitter:title" content="LDS Hymn Stats - Does anyone sing the women’s and men’s arrangements?">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://hymnstats.joeystanley.com/images/womens_mens.jpeg">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">LDS Hymn Stats</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../findings.html" rel="" target="">
 <span class="menu-text">Findings</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../contribute.html" rel="" target="">
 <span class="menu-text">Contribute</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">About Me</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/ldshymnstats" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/JoeyStanley/lds-hymn-stats" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../findings.xml" rel="" target=""><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<p><img src="../images/logo.jpeg" class="img-fluid"></p>
</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#types-of-womens-and-mens-arrangements" id="toc-types-of-womens-and-mens-arrangements" class="nav-link active" data-scroll-target="#types-of-womens-and-mens-arrangements">Types of Women’s and Men’s arrangements</a></li>
  <li><a href="#womens-arrangements" id="toc-womens-arrangements" class="nav-link" data-scroll-target="#womens-arrangements">Women’s arrangements</a></li>
  <li><a href="#mens-arrangements" id="toc-mens-arrangements" class="nav-link" data-scroll-target="#mens-arrangements">Men’s arrangements</a></li>
  <li><a href="#my-recommendations-for-the-next-hymnal" id="toc-my-recommendations-for-the-next-hymnal" class="nav-link" data-scroll-target="#my-recommendations-for-the-next-hymnal">My recommendations for the next hymnal</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Does anyone sing the women’s and men’s arrangements?</h1>
  <div class="quarto-categories">
    <div class="quarto-category">frequency</div>
    <div class="quarto-category">musicology</div>
    <div class="quarto-category">melody</div>
    <div class="quarto-category">tenor line</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Joey Stanley </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 19, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p>At the back of the hymnal, there are 29 hymns that are designated as being for women or for men, either because of the text and/or because of the musical arrangement. This is a continuation from the previous hymnal, which contained many more arrangements, including choir pieces with special piano accompaniment. I don’t think these hymns are intended to be sung as congregational hymns in sacrament meeting and with a few exceptions, I don’t think they’re sung much at all. Let’s look a little closer at these arrangements.</p>
<section id="types-of-womens-and-mens-arrangements" class="level2">
<h2 class="anchored" data-anchor-id="types-of-womens-and-mens-arrangements">Types of Women’s and Men’s arrangements</h2>
<p>We can classify these hymns into a few different categories. First, we can group them based on the type of musical arrangement. Some of the hymns, like <hymn>A Key Was Turned in Latter Days (310)</hymn> or <hymn>Come, All Ye Sons of God (322)</hymn>, look like most other hymns because they’re arranged in a normal SATB format with four voices throughout. Two of the women’s hymns, <hymn>As Sisters in Zion (309)</hymn> and <hymn>We Meet Again As Sisters (311)</hymn>, look a little more like primary songs since the left hand is simplified, which makes sense because it would be somewhat strange to hear men singing either of those two. Similarly, the men’s hymn, <hymn>The Priesthood of Our Lord (320)</hymn> does not have full harmony lines written and appears that it is intended to be sung in unison. These two types of arrangements are both labeled “Women” or “Men” in the hymnal.</p>
<p>The other main type of musical arrangement is where it a special arrangement geared towards the voices of the gender they are for. For the women, this means it’s a SSA arrangement, with the alto on a separate staff as in <hymn>Love At Home (318)</hymn>. The piano gets its own lines, meaning the hymn has a total of four staves, which is potentially confusing for some people at first glance. The men get TTBB arrangements, as in <hymn>Oh Say, What Is Truth? (331)</hymn>. These are written with a tenor clef centered around C, which is essentially a treble clef but down an octave, which is intimidating at first glance and sometimes tricky to play on the piano. We could even further subdivide the men’s arrangements based on which tenor part has the melody. In most of these arrangements, the highest part has the melody, as in <hymn>Come, Come Ye Saints (326)</hymn>. For three of them though, the highest singer gets a harmony line and the melody is below that, as in <hymn>Brightly Beams Our Father’s Mercy (335)</hymn>. The women’s hymn <hymn>The Lord is My Shepherd (316)</hymn> and the men’s hymn <hymn>School Thy Feelings (336)</hymn> does a mix of these two, and the melody switches from one part to another. All of these special arrangements are labeled “Women’s Choir” or “Men’s Choir”.</p>
<p>The other way of classifying these 29 hymns is whether the hymn appears elsewhere in the hymnal or not. This classification is pretty closely correlated with the musical arrangement as well. For example, among the 10 women’s hymns, three are unique to women and don’t appear anywhere else in the hymnal; these three are also the ones arranged in a SATB-like format. The other seven women’s hymns are special arrangements of hymns that occur earlier in the hymnal in a SATB format.</p>
<p>For the men’s hymns, the correlation is not quite so tight. Of the six men’s hymns that are not full TTBB arrangements, four do not occur elsewhere in the hymnal. The last is <hymn>Rise Up, O Men of God (324)</hymn>, which has a unique melody but the same lyrics as the TTBB arrangement, <hymn>Rise Up, O Men of God (323)</hymn>, on the previous page. Of the 14 Men’s Choir arrangements, five are unique and don’t occur elsewhere in the hymnal (like <hymn>See, the Mighty Angel Flying (330)</hymn>), while the rest are arrangements of existing hymns, like <hymn>Come, Come Ye Saints (326)</hymn>, including some pretty infrequently sung hymns, like <hymn>Thy Servants Are Prepared (261)</hymn>. Then of course, <hymn>Brightly Beams Our Father’s Mercy (336)</hymn> has unique lyrics, but the music is the same as <hymn>Should You Feel Inclined to Censure (325)</hymn>.</p>
<p>A summary of all these classifications can be found in <a href="#tbl-womens_hymns">Table&nbsp;1</a> and <a href="#tbl-mens_hymns">Table&nbsp;2</a>.</p>
<div id="tbl-womens_hymns" class="anchored">
<table class="table-striped table-hover table">
<caption>Table&nbsp;1: Women’s Hymns</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 38%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">#</th>
<th style="text-align: left;">Hymn Name</th>
<th style="text-align: center;">Arrangement type</th>
<th style="text-align: center;">Found elsewhere?</th>
<th style="text-align: center;">Sung in Sacrament?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">309</td>
<td style="text-align: left;">As Sisters in Zion</td>
<td style="text-align: center;">Two-Part</td>
<td style="text-align: center;">Unique</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="even">
<td style="text-align: center;">310</td>
<td style="text-align: left;">A Key Was Turned in Latter Days</td>
<td style="text-align: center;">Two-Part</td>
<td style="text-align: center;">Unique</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td style="text-align: center;">311</td>
<td style="text-align: left;">We Meet Again As Sisters</td>
<td style="text-align: center;">Two-Part</td>
<td style="text-align: center;">Unique</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td style="text-align: center;">312</td>
<td style="text-align: left;">We Ever Pray for Thee</td>
<td style="text-align: center;">SSA</td>
<td style="text-align: center;">Hymn 23</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td style="text-align: center;">313</td>
<td style="text-align: left;">God is Love</td>
<td style="text-align: center;">SSA</td>
<td style="text-align: center;">Hymn 87</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td style="text-align: center;">314</td>
<td style="text-align: left;">How Gentle God’s Commands</td>
<td style="text-align: center;">SSA</td>
<td style="text-align: center;">Hymn 125</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td style="text-align: center;">315</td>
<td style="text-align: left;">Jesus, the Very Thought of Thee</td>
<td style="text-align: center;">SSA</td>
<td style="text-align: center;">Hymn 141</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td style="text-align: center;">316</td>
<td style="text-align: left;">The Lord is My Shepherd</td>
<td style="text-align: center;">SSA</td>
<td style="text-align: center;">Hymn 108</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td style="text-align: center;">317</td>
<td style="text-align: left;">Sweet is the Work</td>
<td style="text-align: center;">SSA</td>
<td style="text-align: center;">Hymn 147</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td style="text-align: center;">318</td>
<td style="text-align: left;">Love at Home</td>
<td style="text-align: center;">SSA</td>
<td style="text-align: center;">Hymn 294</td>
<td style="text-align: center;">yes</td>
</tr>
</tbody>
</table>
</div>
<div id="tbl-mens_hymns" class="anchored">
<table class="table-striped table-hover table">
<caption>Table&nbsp;2: Men’s Hymns. Asterisks indicate which tenor part has the melody.</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 36%">
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">#</th>
<th>Hymn name</th>
<th style="text-align: center;">Arrangement type</th>
<th style="text-align: center;">Found elsewhere?</th>
<th style="text-align: center;">Sung in Sacrament?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">319</td>
<td>Ye Elders of Israel</td>
<td style="text-align: center;">Men</td>
<td style="text-align: center;">Unique</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="even">
<td style="text-align: center;">320</td>
<td>The Priesthood of Our Lord</td>
<td style="text-align: center;">Men (unison)</td>
<td style="text-align: center;">Unique</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="odd">
<td style="text-align: center;">321</td>
<td>Ye Who Are Called to Labor</td>
<td style="text-align: center;">Men</td>
<td style="text-align: center;">Unique</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td style="text-align: center;">322</td>
<td>Come, All Ye Sons of God</td>
<td style="text-align: center;">Men</td>
<td style="text-align: center;">Unique</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="odd">
<td style="text-align: center;">323</td>
<td>Rise Up, O Men of God</td>
<td style="text-align: center;">T*TBB</td>
<td style="text-align: center;">Hymn 324 (lyrics)</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td style="text-align: center;">324</td>
<td>Rise Up, O Men of God</td>
<td style="text-align: center;">Men</td>
<td style="text-align: center;">Hymn 323 (lyrics)</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="odd">
<td style="text-align: center;">325</td>
<td>See the Mighty Priesthood Gathered</td>
<td style="text-align: center;">T*TBB</td>
<td style="text-align: center;">Unique</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="even">
<td style="text-align: center;">326</td>
<td>Come, Come Ye Saints</td>
<td style="text-align: center;">T*TBB</td>
<td style="text-align: center;">Hymn 30</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td style="text-align: center;">327</td>
<td>Go, Ye Messengers of Heaven</td>
<td style="text-align: center;">T*TBB</td>
<td style="text-align: center;">Unique</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="even">
<td style="text-align: center;">328</td>
<td>An Angel from on High</td>
<td style="text-align: center;">T*TBB</td>
<td style="text-align: center;">Hymn 13</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td style="text-align: center;">329</td>
<td>Thy Servants are Prepared</td>
<td style="text-align: center;">TT*BB</td>
<td style="text-align: center;">Hymn 261</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td style="text-align: center;">330</td>
<td>See, the Mighty Angel Flying</td>
<td style="text-align: center;">T*TBB</td>
<td style="text-align: center;">Unique</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td style="text-align: center;">331</td>
<td>Oh Say, What Is Truth?</td>
<td style="text-align: center;">T*TBB</td>
<td style="text-align: center;">Hymn 272</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td style="text-align: center;">332</td>
<td>Come, O Thou King of Kings</td>
<td style="text-align: center;">T*TBB</td>
<td style="text-align: center;">Hymn 59</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td style="text-align: center;">333</td>
<td>High on the Mountain Top</td>
<td style="text-align: center;">T*TBB</td>
<td style="text-align: center;">Hymn 5</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td style="text-align: center;">334</td>
<td>I Need Thee Every Hour</td>
<td style="text-align: center;">TT*BB</td>
<td style="text-align: center;">Hymn 98</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td style="text-align: center;">335</td>
<td>Brightly Beams Our Father’s Mercy</td>
<td style="text-align: center;">TT*BB</td>
<td style="text-align: center;">Hymn 235 (music)</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="even">
<td style="text-align: center;">336</td>
<td>School Thy Feelings</td>
<td style="text-align: center;">T*T*BB</td>
<td style="text-align: center;">Unique</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="odd">
<td style="text-align: center;">337</td>
<td>O Home Beloved</td>
<td style="text-align: center;">T*TBB</td>
<td style="text-align: center;">Unique</td>
<td style="text-align: center;">no</td>
</tr>
</tbody>
</table>
</div>
<p>Let’s now turn to the actual question of which of these are actually sung in sacrament meeting.</p>
</section>
<section id="womens-arrangements" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="womens-arrangements">Women’s arrangements</h2>
<div class="page-columns page-full"><p>Just two of the women’s hymns were ever sung in sacrament meeting in my sample. <hymn>As Sisters in Zion (309)</hymn> was sung eight times, which is actually more often than almost 100 other hymns. So, still quite unusual—about once every 14 years on average—but more common than many other hymns (see <a href="#fig-womens_mens">Figure&nbsp;1</a>). The other women’s hymn that was sung in sacrament meeting was <hymn>Love at Home (318)</hymn>. This though was sung just one time in all my data. I don’t know the circumstances surrounding it, but I can’t help but wonder if it was a mistake and the music coordinator intended to just do Hymn 294.</p><div class="no-row-height column-margin column-container"><span class="">Hymn 318 was actually sung in the ward next door to me, but before I moved in. I suppose I could ask!</span></div></div>
<p>There’s really not much more to say about the women’s arrangements! They’re hardly ever sung!</p>
<div id="fig-womens_mens" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="../images/womens_mens.jpeg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Women’s and men’s arrangements</figcaption>
</figure>
</div>
</section>
<section id="mens-arrangements" class="level2">
<h2 class="anchored" data-anchor-id="mens-arrangements">Men’s arrangements</h2>
<p>The men’s hymns appear to have a bit more currency in sacrament meetings than the women’s hymns (see <a href="#fig-womens_mens">Figure&nbsp;1</a>). Seven of these 19 hymns were sung in at least one of the sacrament meetings in my sample. The most common was <hymn>Brightly Beams Our Father’s Mercy (335)</hymn>, which was sung, on average, once every six years, or about as often as something like <hymn>That Easter Morn (198)</hymn>. Even though it is somewhat familiar to many Latter-day Saints, it would probably be somewhat confusing for some people to sing it in sacrament meeting because it is arranged such that what appears to be the “soprano” part is actually a harmony line. Next was <hymn>Ye Elders of Israel (319)</hymn>, which was sung 10 times in my sample. The others were only sung once or twice. Musically, the hymns <hymn>Come, All Ye Sons of God (322)</hymn> and <hymn>Rise Up, O Men of God (324)</hymn> are like <hymn>Ye Elders of Israel (319)</hymn> and would be less awkward to sing in church because their arrangements are perfectly fine as SATB and wouldn’t throw off the organist or the congregants. But, it would be very strange to sing <hymn>See the Mighty Priesthood Gathered (325)</hymn> and <hymn>Go, Ye Messengers of Heaven (327)</hymn> because either the melody is in the “alto” line, like <hymn>Brightly Beams Our Father’s Mercy (335)</hymn>, or the melody is too high for a typical member to sing since it is arranged for a high tenor.</p>
</section>
<section id="my-recommendations-for-the-next-hymnal" class="level2">
<h2 class="anchored" data-anchor-id="my-recommendations-for-the-next-hymnal">My recommendations for the next hymnal</h2>
<p>To summarize, very few of the women’s and men’s arrangements are sung in sacrament meeting, and those that are are rarely done so. Based on this data, I believe these hymns should probably just be removed from the hymnal. There is little reason to print tens of thousands of these 29 hymns that hardly anyone uses. As mentioned above, the previous version of the hymnal had more arrangements—some of which were full-on choir pieces—and they were removed in this 1985 edition. It makes sense to continue that trend. We don’t need to remove them completely though—I think they should be part of an online-only supplement that would be accessible through the church’s apps and website.</p>
<p>It may be the case that these hymns were kept in the hymnal with the intention of them being sung in Relief Society and Elders Quorum meetings. But now that we do not begin those meetings with hymns anymore, there is little reason to keep them. Maybe there is value in singing one of these hymns in some stake priesthood meeting or a women’s session of General Conference, and if the hymnal is treated as “canon” for what can or cannot be sung in church meetings, then it might be worth it to keep some in there simply to hold their place as canon. In my opinion though, an online supplement can serve that purpose.</p>
<p>Some of these hymns can and probably should be repurposed and brought into the main collection of hymns. For example, <hymn>Brightly Beams Our Father’s Mercy (335)</hymn> appears to be the most common of these 29 hymns and it would be a shame to lose it. But, there is no reason to keep it as a men’s-only arrangement: simply rearrange it as an SATB piece and I suspect it could become a more popular one.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">Copyright 2023, Joey Stanley</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>