{
  "hash": "1b5281cbb29c7dd4ce184a8309ae8213",
  "result": {
    "markdown": "---\ntitle: \"What are the most and least common Sacrament Hymns?\"\ndescription: \"In this post, I dive into just the canonical sacrament hymns (i.e. hymns 169--196).\"\nauthor: \"Joey Stanley\"\ndate: \"9/7/23\"\ndate-modified: 10-16-2023\ncategories:\n  - sacrament\n  - frequency\naliases:\n  - findings.html#sacrament-hymns\n---\n\n\n\n\nWe'll start off by looking at sacrament hymns, or rather, the hymn sung immediately before the sacrament is blessed and passed to the congregation. As far as I can tell, §19.3.2 of the *General Handbook* has the only instruction about sacrament hymns, and it says that \"\\[t\\]he sacrament hymn should refer to the sacrament itself or to the sacrifice of the Savior.\" This instruction is repeated on page 380 of the hymnal.\n\nIn the hymnal, sacrament hymns go from 169 (<hymn>As Now We Take the Sacrament</hymn>) to 196 (<hymn>Jesus, Once of Humble Birth</hymn>), at least according to the Table of Contents. As far as I can tell, it doesn't *specifically* state that the sacrament hymn must be one of the 28 within that range, but I think it's a generally accepted that that's what that phrase from the handbook means.[In fact, I've had church leaders enforce this constraint. I was in a ward where a newly-called music coordinator chose reverent hymns that were outside of that range. After about two weeks, the bishop announced that we'd be singing a different hymn than what was listed on the program and he changed it to a sacrament hymn. Presumably he later explained the policy to the chorister afterwards because we sang \"true\" sacrament hymns from then on.]{.aside}\n\n\n\n\n\n\n\nAs [I've written already](/posts/most_common), <hymn>I Stand All Amazed (193)</hymn> is the most common hymn overall. So it should come as no surprise that a sacrament hymn is the most common hymn overall. It focuses less on the sacrament itself and more on the Atonement, so it could be used outside of sacrament contexts without feeling out of place. In fact, a quick look at the numbers suggests that it was, in fact, sung as opening and closing hymns at least three times more often than any other sacrament hymn. This may explain why it stands out as the most commonly sung hymn in sacrament meetings.\n\n\n\n## Frequency\n\nLet's take a closer look at the sacrament hymns themselves. In theory, if a ward were to systematically cycle through all the sacrament hymns, they'd make it through all of them in a little over six months. However, this plot shows that they're definitely not all sung equally as often as each other.\n\n[Many plots throughout this blog are formatted just like this one here. Hymns that are less common are in the lower left and hymns that are more common are in the upper right. The numbers along the bottom refer to how many times, on average, a ward will sing that hymn within a given year.]{.aside}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=768}\n:::\n:::\n\n\n\n:::{.callout-tip collapse=\"true\"}\n\n### Click to show the summarized data\n\n\n::: {.cell}\n::: {.cell-output-display}\n| Rank|Title                                 |Number |    n| Average per year| Every X weeks| Every X months| Every X years|\n|----:|:-------------------------------------|:------|----:|----------------:|-------------:|--------------:|-------------:|\n|    1|I Stand All Amazed                    |193    | 1029|            2.689|        17.850|          4.463|         0.372|\n|    2|In Humility, Our Savior               |172    |  940|            2.456|        19.540|          4.885|         0.407|\n|    3|Jesus, Once of Humble Birth           |196    |  899|            2.349|        20.432|          5.108|         0.426|\n|    4|There Is a Green Hill Far Away        |194    |  889|            2.323|        20.661|          5.165|         0.430|\n|    5|As Now We Take the Sacrament          |169    |  862|            2.253|        21.309|          5.327|         0.444|\n|    6|How Great the Wisdom and the Love     |195    |  825|            2.156|        22.264|          5.566|         0.464|\n|    7|God, Our Father, Hear Us Pray         |170    |  779|            2.036|        23.579|          5.895|         0.491|\n|    8|God Loved Us, So He Sent His Son      |187    |  772|            2.017|        23.793|          5.948|         0.496|\n|    9|O God, the Eternal Father             |175    |  769|            2.010|        23.886|          5.971|         0.498|\n|   10|We'll Sing All Hail to Jesus' Name    |182    |  762|            1.991|        24.105|          6.026|         0.502|\n|   11|Jesus of Nazareth, Savior and King    |181    |  758|            1.981|        24.232|          6.058|         0.505|\n|   12|Father in Heaven, We Do Believe       |180    |  752|            1.965|        24.426|          6.106|         0.509|\n|   13|Upon the Cross of Calvary             |184    |  684|            1.787|        26.854|          6.713|         0.559|\n|   14|With Humble Heart                     |171    |  683|            1.785|        26.893|          6.723|         0.560|\n|   15|Behold the Great Redeemer Die         |191    |  679|            1.774|        27.052|          6.763|         0.564|\n|   16|Reverently and Meekly Now             |185    |  677|            1.769|        27.131|          6.783|         0.565|\n|   17|In Memory of the Crucified            |190    |  616|            1.610|        29.818|          7.455|         0.621|\n|   18|While of These Emblems We Partake     |174    |  613|            1.602|        29.964|          7.491|         0.624|\n|   19|He Died! The Great Redeemer Died      |192    |  601|            1.571|        30.562|          7.641|         0.637|\n|   20|'Tis Sweet to Sing the Matchless Love |177    |  571|            1.492|        32.168|          8.042|         0.670|\n|   21|In Remembrance of Thy Suffering       |183    |  482|            1.260|        38.108|          9.527|         0.794|\n|   22|'Tis Sweet to Sing the Matchless Love |176    |  473|            1.236|        38.833|          9.708|         0.809|\n|   23|Thy Will, O Lord, Be Done             |188    |  468|            1.223|        39.248|          9.812|         0.818|\n|   24|While of These Emblems We Partake     |173    |  457|            1.194|        40.193|         10.048|         0.837|\n|   25|O Lord of Hosts                       |178    |  388|            1.014|        47.340|         11.835|         0.986|\n|   26|Again, Our Dear Redeeming Lord        |179    |  328|            0.857|        56.000|         14.000|         1.167|\n|   27|Again We Meet Around the Board        |186    |  304|            0.794|        60.421|         15.105|         1.259|\n|   28|O Thou, Before the World Began        |189    |  232|            0.606|        79.172|         19.793|         1.649|\n:::\n:::\n\n\n\n:::\n\nJoining <hymn>I Stand All Amazed (193)</hymn> as the most common ones are <hymn>In Humility, Our Savior (172)</hymn>, <hymn>Jesus, Once of Humble Birth (196)</hymn>, and <hymn>There is a Green Hill Far Away (194)</hymn>. These and a few others are each sung around two or three times per year, on average, or once every three and a half to four and a half months.\n\nMost sacrament hymns are sung at least once a year per ward, on average, but there were some that were less common. <hymn>O Lord of Hosts (178)</hymn>, <hymn>Again, Our Dear Redeeming Lord (179)</hymn>, and <hymn>Again, We Meet around the Board (186)</hymn> each averaged somewhere between once every 11 and 15 months. The least frequent sacrament hymn though was <hymn>O Thou, Before the World Began (189)</hymn>, showing up a little more often than once every two years.\n\n\n\n\n\n\n\n\n## Non-sacrament hymns\n\n\nOnce in a while, a ward will indeed sing some other hymn as a sacrament hymn. Many hymns were selected by at least one ward at least one time, but two stood out. They are <hymn>O Savior, Thou Who Wearest a Crown (197)</hymn> and <hymn>Gently Raise the Sacred Strain (146)</hymn>. There is good reason for why these two were sung as sacrament hymns: if you look up \"Sacrament\" in the topical index in the back of the hymnal, it is a list of all the hymns from 169--196, but it also includes these two.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=768}\n:::\n:::\n\n\nLet's start with <hymn>O Savior, Thou Who Wearest a Crown (197)</hymn>. It was sung *as a sacrament hymn* about once every two per ward on average. Given that it feels like a sacrament hymn *and* like an Easter hymn, it is perfectly placed between the more on-the-nose sacrament hymns (i.e. those about the bread and water) and the more traditional Easter hymns (e.g. <hymn>He is Risen! (199)</hymn>). Perhaps some music coordinators noticed it in the Index and chose it because of that. But, I could see a music coordinator selecting it because they perhaps thought sacrament hymns went from 169--197 instead of 169--196.\n\n\n\n\n\n\nThe oddball though is <hymn>Gently Raise the Sacred Strain (146)</hymn>. In fact, it was sung *as a sacrament hymn* about once every 2.6 years per ward, which is only a little less often than <hymn>O Thou, Before the World Began (189)</hymn>. It is not clear to me why this one is listed in the index as a sacrament hymn, but it's not grouped together with the other sacrament hymns. The \"Prayer and Supplication\" category of hymns, which is what this is a part of (and rightfully so, in my opinion), is just before the \"Sacrament\" category. If it, like <hymn>O Savior, Thou Who Wearest a Crown (197)</hymn>, fits into both categories, then I think it should be moved to hymn 168 so that it's less out of left field. This one really should be thought of as an honorary sacrament hymn. Perhaps we'll see it included in the \"official\" list of sacrament hymns in the next hymnal.\n\n::: callout-tip\n### Recommendation for the next hymnal\n\nConsider putting <hymn>O Thou, Before the World Began (189)</hymn> immediately before the list of sacrament hymns.\n:::\n\n\n## Sacrament hymns sung elsewhere\n\n\n\n\n\nHow often will a ward do this, on average, across all sacrament hymns?\n\n\n\n\n\nFinally, we can look at sacrament hymns that were sung at some other point in a sacrament meeting. Unsurprisingly, <hymn>I Stand All Amazed (193)</hymn> is at the top, being sung occasionally as an opening hymn and closing hymn. At only once every 5--6 years, it's not particularly common to see it sung this way, but it's still not unheard of. After that, there are a few others like <hymn>'Tis Sweet to Sing the Matchless Love (177)</hymn> and <hymn>Reverently and Meekly Now (185)</hymn> were also used as one of the other hymns, but it was still quite unusual.\n\nOverall, while singing a specific sacrament hymn elsewhere in the meeting is pretty unusual, the odds of singing *any* of the sacrament hymns is more common since their frequencies add together. It happened in 226 of the 17,833 sacrament meetings I have data from, or 1.3% of them. That means, on average, a ward might since hymn 169--196 at some other point in the meeting approximately once every year and 8 months.\n\n## Conclusion\n\nThe findings in this section suggest that were have a strong tradition of singing hymns 169 through 196 in our sacrament meetings immediately before the sacrament itself. Some wards systematically cycle through them, which I believe is a perfectly appropriate thing to do to include the widest variety of hymns to the ward. Other wards pick and choose, which inevitably leads to some favorites being sung more and some lesser-known ones falling through the cracks.\n\nAs we'll see when we look at holidays, wards do not always stick to the table of contents at the beginning of the hymnal when choosing appropriate hymns. However, in the case of the sacrament---which is the most important part of our Sunday worship and the primary reason for Sunday gatherings---it's clear that we adhere strongly to the recommendation. Nevertheless, the addition of <hymn>Gently Raise the Sacred Strain (146)</hymn> shows that there is at least some room for thinking out of the box when selecting sacrament hymns.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}