<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Joey Stanley">
<meta name="dcterms.date" content="2024-07-04">

<title>LDS Hymn Stats - What hymns are sung around the 4th of July</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-SG4E42NZ2F"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-SG4E42NZ2F', { 'anonymize_ip': true});
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="LDS Hymn Stats - What hymns are sung around the 4th of July">
<meta property="og:description" content="">
<meta property="og:image" content="https://hymnstats.joeystanley.com/posts/4th_of_july/index_files/figure-html/fig-most_common-1.png">
<meta property="og:site-name" content="LDS Hymn Stats">
<meta property="og:image:height" content="576">
<meta property="og:image:width" content="1536">
<meta name="twitter:title" content="LDS Hymn Stats - What hymns are sung around the 4th of July">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://hymnstats.joeystanley.com/posts/4th_of_july/index_files/figure-html/fig-most_common-1.png">
<meta name="twitter:image-height" content="576">
<meta name="twitter:image-width" content="1536">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">LDS Hymn Stats</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../findings.html" rel="" target="">
 <span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../overview.html" rel="" target="">
 <span class="menu-text">Summarized Data</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../contribute.html" rel="" target="">
 <span class="menu-text">Contribute</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About Me</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/ldshymnstats" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/JoeyStanley/lds-hymn-stats" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../findings.xml" rel="" target=""><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<p><img src="../../images/logo.jpeg" class="img-fluid"></p>
</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-top-3-patriotic-hymns" id="toc-the-top-3-patriotic-hymns" class="nav-link active" data-scroll-target="#the-top-3-patriotic-hymns">The top 3 patriotic hymns</a></li>
  <li><a href="#other-patriotic-hymns" id="toc-other-patriotic-hymns" class="nav-link" data-scroll-target="#other-patriotic-hymns">Other patriotic hymns</a></li>
  <li><a href="#when-during-sacrament-meeting-are-these-hymns-sung" id="toc-when-during-sacrament-meeting-are-these-hymns-sung" class="nav-link" data-scroll-target="#when-during-sacrament-meeting-are-these-hymns-sung">When during sacrament meeting are these hymns sung?</a></li>
  <li><a href="#when-is-the-4th-of-july-season" id="toc-when-is-the-4th-of-july-season" class="nav-link" data-scroll-target="#when-is-the-4th-of-july-season">When is the 4th of July “season”?</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">What hymns are sung around the 4th of July</h1>
  <div class="quarto-categories">
    <div class="quarto-category">holidays</div>
    <div class="quarto-category">frequency</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Joey Stanley </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 4, 2024</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">July 5, 2024</p>
    </div>
  </div>
    
  </div>
  

</header>

<p>Today is Independence Day in the United States. Many American congregations sing patriotic hymns to commemorate the day. Let’s take a look at some statistics and patterns around the 4th of July. This post is based on data from 817 sacrament meetings within seven days of July 4th between 2002 and 2024. They come from 310 wards in the United States.</p>
<section id="the-top-3-patriotic-hymns" class="level2">
<h2 class="anchored" data-anchor-id="the-top-3-patriotic-hymns">The top 3 patriotic hymns</h2>
<p>It is no surprise what the top three most common hymns within a week of July 4th are. Just about two-thirds of wards sing <hymn>America the Beautiful (#338)</hymn>. Over half sing <hymn>My Country, ’Tis of Thee (#339)</hymn>, and about 43% sing the <hymn>The Star-Spangled Banner (#340)</hymn>.</p>
<p>That’s a remarkably high percentage of wards. It’s rare to see holidays with that amount of consistency. For reference less about 58% of wards sing <hymn>He is Risen! (#199)</hymn> around Easter and about half sing <hymn>Come, Let Us Anew (#217)</hymn> around New Year’s. The only other holiday I’ve seen with that amount of consistency is Thanksgiving, where about 74% of wards sing <hymn>Come, Ye Thankful People (#94)</hymn> and about 68% sing <hymn>Prayer of Thanksgiving (#93)</hymn>. This may have something to do with patriotism, but it may simply be because there are relatively few hymns to choose from and only one or two weeks to use them.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Technical details for nerds :)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If about 66% of wards sing 338, 53% sing 339, and 43% sing 340, then we would expect <span class="math inline">\(0.66 \times 0.53 \times 0.43 = 15\%\)</span> of wards go for the trifecta and sing all three. We actually do not see that many. In fact, I’ve only seen that happen in just seven wards, or 0.9% of sacrament meetings around July 4th. A part of me wants to run some analysis to show that the probabilities of hymns are not independent and that conditional probability of the hymns goes down given that one or two of the others is already sung. But, I took a look at those seven meetings and saw a more practical explanation.</p>
<p>First, the Sunday closest to July 4th is most often a Fast and Testimony meeting, which means an intermediate hymn is not (or at least very rarely) sung. I have no instances of any of these three hymns being sung as a sacrament hymn, which makes sense since it’d be rather inappropriate to do so. So, that leaves just two slots for congregational hymns. Nevertheless, one ward in Kansas City, Missouri sang all three on July 2nd, 2017—most likely a Fast Sunday—so it’s not completely unheard of. But it likely deters most other wards.</p>
<p>So, the only chance you’ve got of singing these hymns is if the Sunday before the 4th of July is in June, not July. Of those seven meetings with all three of those hymns, the other six of them were on June 30th. As we’ll see below, June 30th is close to the earliest time we typically see patriotic hymns. If June 29th is on a Sunday, then the 4th of July is a Friday, and most people sing patriotic hymns the following Sunday, on the 6th, rather than before. We also get some interference with hymns related to <a href="../../posts/martyrdom">the martyrdom of Joseph Smith</a>.</p>
<p>Also, since 2002, which when is the earliest data I have came from, June 30th has fallen on a Sunday four times: 2002, 2013, 2019, and 2024. I have very little data from 2002, so it’s surprising that none of the trifecta sacrament meetings were from then. I don’t have a ton of data from 2013 or 2019, but one of those seven did come from 2013. The five of the others are from 2024, which makes sense because it’s the year with the second most amount of data in my sample, and by far the year of those four that I have the most data from.</p>
<p>However, there may be an additional piece of the puzzle. Prior to about June 2024, a big chunk of <a href="../../posts/frequency-data">my data</a> came from people sending me their ward’s spreadsheets. A lot of it also came from weekly contributions by various donors. But, nearly 100% of the data came from people who cared enough about their hymns to report it. Starting around the time the first batch of the new hymns were released, I started looking through YouTube to get data from wards that still post live streams of their meetings.</p>
<p>This is an interesting development and it’ll warrant some additional analysis later on. If people send in a spreadsheet of their ward’s hymns, that mere fact means that their ward has a spreadsheet to keep track of hymns. Presumably, they use that spreadsheet to avoid repeating hymns too often. So, I’m assuming there is a pretty significant sampling bias in my data: wards that have spreadsheets are less likely to repeat hymns than wards without spreadsheets. I don’t know whether the wards I get data from off of YouTube use spreadsheets to keep track of their hymns. But some of them might not. The point is, they are likely a more representative sample of what hymns are being sung look like.</p>
<p>So, it just so happens that the five wards from 2024 that did a trifecta of singing all three patriotic hymns in a single meeting were ones I got from YouTube. Again, it could just be a sampling size thing: I have more data from 2024 so I’m more likely to find it. But, it could also be that some of these wards don’t have spreadsheets to keep track of their ward’s hymn data, so they’re unable to say, “oh, y’know what, we sang that hymn last year, let’s sing a different one this year.” In other words, they go by gut feeling, inspiration, or just vibes, rather than history to choose hymns.</p>
<p>Anyway, all this is to say that even though a significant number of wards sing each of those three patriotic hymns each year, very few sing all three of them in one meeting.</p>
</div>
</div>
</div>
</section>
<section id="other-patriotic-hymns" class="level2">
<h2 class="anchored" data-anchor-id="other-patriotic-hymns">Other patriotic hymns</h2>
<p><a href="#fig-most_common">Figure&nbsp;1</a> below shows the most common hymns (excluding sacrament hymns) within a week of Jul 4th, and what percentage of wards sing them each year. At the top are the three hymns we’ve already discussed. But, coming in fourth and fifth places are <hymn>Battle Hymn of the Republic (#60)</hymn> and <hymn>God Of Our Fathers, Whose Almighty Hand (#78)</hymn>. In the figure, I’ve included the top dozen or so most popular hymns, not because I’m interested in which hymns are beyond those top five (because they’re just generic common hymns), but because I want to show just how much more popular these top five are compared to everything else.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-most_common" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/fig-most_common-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Most common hymns around July 4th and how many wards sing them each year</figcaption>
</figure>
</div>
</div>
</div>
<p>So, if you’re looking for additional hymns to sing around Independence Day, these might be good ones to choose from. Incidentally—and I haven’t done a blog post on this yet—but those two are also among the most common around Memorial Day in the United States, further supporting their status as “honorary” patriotic hymns.</p>
<p>With that said, there are a couple other hymns that might be considered 4th of July hymns, even if they’re not super popular. One is <hymn>Know This, That Every Soul Is Free (#240)</hymn>. It’s not a super common hymn (it’s only sung about once every 4.3 years per ward), but if it is sung, it’s 3.33 times more likely to be done so within a week of July 4th than during the rest of the year combined. This and other hymns more likely to be sung around July 4th are shown below:</p>
<div class="cell">
<div class="cell-output-display">

<div id="udwufonlku" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#udwufonlku table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#udwufonlku thead, #udwufonlku tbody, #udwufonlku tfoot, #udwufonlku tr, #udwufonlku td, #udwufonlku th {
  border-style: none;
}

#udwufonlku p {
  margin: 0;
  padding: 0;
}

#udwufonlku .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#udwufonlku .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#udwufonlku .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#udwufonlku .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#udwufonlku .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#udwufonlku .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#udwufonlku .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#udwufonlku .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#udwufonlku .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#udwufonlku .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#udwufonlku .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#udwufonlku .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#udwufonlku .gt_spanner_row {
  border-bottom-style: hidden;
}

#udwufonlku .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#udwufonlku .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#udwufonlku .gt_from_md > :first-child {
  margin-top: 0;
}

#udwufonlku .gt_from_md > :last-child {
  margin-bottom: 0;
}

#udwufonlku .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#udwufonlku .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#udwufonlku .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#udwufonlku .gt_row_group_first td {
  border-top-width: 2px;
}

#udwufonlku .gt_row_group_first th {
  border-top-width: 2px;
}

#udwufonlku .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#udwufonlku .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#udwufonlku .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#udwufonlku .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#udwufonlku .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#udwufonlku .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#udwufonlku .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#udwufonlku .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#udwufonlku .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#udwufonlku .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#udwufonlku .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#udwufonlku .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#udwufonlku .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#udwufonlku .gt_left {
  text-align: left;
}

#udwufonlku .gt_center {
  text-align: center;
}

#udwufonlku .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#udwufonlku .gt_font_normal {
  font-weight: normal;
}

#udwufonlku .gt_font_bold {
  font-weight: bold;
}

#udwufonlku .gt_font_italic {
  font-style: italic;
}

#udwufonlku .gt_super {
  font-size: 65%;
}

#udwufonlku .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#udwufonlku .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#udwufonlku .gt_indent_1 {
  text-indent: 5px;
}

#udwufonlku .gt_indent_2 {
  text-indent: 10px;
}

#udwufonlku .gt_indent_3 {
  text-indent: 15px;
}

#udwufonlku .gt_indent_4 {
  text-indent: 20px;
}

#udwufonlku .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_heading">
      <td colspan="2" class="gt_heading gt_title gt_font_normal" style="">Hymns most likely be sung around July 4th</td>
    </tr>
    <tr class="gt_heading">
      <td colspan="2" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style="">Compared to the rest of the year combined</td>
    </tr>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="hymn">hymn</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="times more likely">times more likely</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="hymn" class="gt_row gt_left">The Star-Spangled Banner (340)</td>
<td headers="times more likely" class="gt_row gt_right">206.68</td></tr>
    <tr><td headers="hymn" class="gt_row gt_left">My Country, 'Tis of Thee (339)</td>
<td headers="times more likely" class="gt_row gt_right">91.62</td></tr>
    <tr><td headers="hymn" class="gt_row gt_left">America the Beautiful (338)</td>
<td headers="times more likely" class="gt_row gt_right">73.34</td></tr>
    <tr><td headers="hymn" class="gt_row gt_left">Battle Hymn of the Republic (60)</td>
<td headers="times more likely" class="gt_row gt_right">15.72</td></tr>
    <tr><td headers="hymn" class="gt_row gt_left">God of Our Fathers, Whose Almighty Hand (78)</td>
<td headers="times more likely" class="gt_row gt_right">8.02</td></tr>
    <tr><td headers="hymn" class="gt_row gt_left">Jehovah, Lord of Heaven and Earth (269)</td>
<td headers="times more likely" class="gt_row gt_right">3.40</td></tr>
    <tr><td headers="hymn" class="gt_row gt_left">Know This, That Every Soul Is Free (240)</td>
<td headers="times more likely" class="gt_row gt_right">3.33</td></tr>
    <tr><td headers="hymn" class="gt_row gt_left">O Ye Mountains High (34)</td>
<td headers="times more likely" class="gt_row gt_right">2.68</td></tr>
    <tr><td headers="hymn" class="gt_row gt_left">Faith of Our Fathers (84)</td>
<td headers="times more likely" class="gt_row gt_right">2.02</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
<p>So, looking at the data this way, we can see hymns that are maybe not as common but still might be thought of as a patriotic hymns still. It’s worth noting that <hymn>The Star-Spangled Banner (#340)</hymn> is so much more likely than the others because the others are occasionally sung during other times of the year, like around Memorial Day and Veterans Day, but the national anthem is not. It seems like the national anthem is almost exclusively sung as a congregational hymn around July 4th.</p>
<p>Here’s my prediction for the future. We know the new hymnal will be worldwide, so I doubt we’ll see hymns 338–340 in the new hymnal. (So, if you like singing them in church, you’ve got two more years to do so!) Some wards may choose to continue singing them as extra-canonical hymns, just as Canadians sometimes sing “O Canada”. But my guess is most wards will not. What will they sing then? Probably some of these hymns: <hymn>Battle Hymn of the Republic (#60)</hymn>, <hymn>God of Our Fathers, Whose Almighty Hand (#78)</hymn>, <hymn>Know This, That Every Soul Is Free (#240)</hymn>, and <hymn>Faith of Our Fathers (#84)</hymn>.</p>
</section>
<section id="when-during-sacrament-meeting-are-these-hymns-sung" class="level2">
<h2 class="anchored" data-anchor-id="when-during-sacrament-meeting-are-these-hymns-sung">When during sacrament meeting are these hymns sung?</h2>
<p>Now that we’ve established what the patriotic hymns are, let’s see when during sacrament meeting they’re sung. <a href="#fig-types">Figure&nbsp;2</a> shows the top five hymns around the 4th of July and when they’re sung in sacrament meeting. Intermediate hymns are rare because of Fast Sunday, so it’s mostly a split between opening and closing hymns.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-types" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/fig-types-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption class="figure-caption">Figure&nbsp;2: When during sacrament the top five patriotic hymns are sung</figcaption>
</figure>
</div>
</div>
</div>
<p>Most hymns are pretty balanced, though each as their own tendencies. <hymn>America the Beautiful (#338)</hymn>, <hymn>Battle Hymn of the Republic (#60)</hymn>, and <hymn>God of Our Fathers, Whose Almighty Hand (#78)</hymn> are a little bit more common as opening hymns while <hymn>My Country, ’Tis of Thee (#339)</hymn> and <hymn>The Star-Spangled Banner (#340)</hymn> are a little more common as closing hymns.</p>
</section>
<section id="when-is-the-4th-of-july-season" class="level2">
<h2 class="anchored" data-anchor-id="when-is-the-4th-of-july-season">When is the 4th of July “season”?</h2>
<p>Finally, we can look at when the “season” of singing patriotic hymns starts and ends. Sunday was June 30th this year, but because I have data spanning multiple years, I can see how common these hymns are on July 1st, July 2nd, etc. on years when Sunday falls on those days.</p>
<p>Overall, we see that there is a very clear rise and fall (<a href="#fig-by_date">Figure&nbsp;3</a>). It is centered right around July 3rd and July 4th, meaning you’re most likely to sing the most number of patriotic congregational hymns on or just before Independence Day itself. Notice that the peak is around 60%. That means that 60% of congregational hymns on July 3rd—across all my wards in the United States that I have data from for this week—were one of the top five I’ve talked about already. It’s Fast Sunday, so there is no intermediate hymn, and the sacrament hymn won’t be a patriotic hymn, so the max it could be is 67%. The fact that it’s so close to the theoretical max is pretty astounding actually.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-by_date" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/fig-by_date-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Proportion of patriotic congregational hymns by date</figcaption>
</figure>
</div>
</div>
</div>
<p>The further the Sunday is from the 4th, the less likely you are to sing many patriotic hymns. There was some discussion on social media among LDS music coordinators this year about whether patriotic hymns should come the Sunday before (June 30th) or the Sunday after (July 7th). When the 4th is in the middle of the week, like a Thursday, neither option feel right. As you can see on this chart, the data shows that wards are split about 50-50: 27% of hymns on June 30th are patriotic while 22% are on July 7th. Of course, June 30th is much more likely to have an intermediate hymn. However, when I reran the plot based on raw <em>number</em> of patriotic hymns (1, 2, or 3), the 30th has a slight edge (see <a href="#fig-by_date_number">Figure&nbsp;4</a>, below)</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Click to see that plot
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output-display">
<div id="fig-by_date_number" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/fig-by_date_number-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption class="figure-caption">Figure&nbsp;4: Number of patriotic congregational hymns by date</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>The other interesting thing about <a href="#fig-by_date">Figure&nbsp;3</a> is that you can see when the 4th of July “season” starts and stops. We get really very few patriotic congregational hymns before June 25th. Given that the 27th is the Sunday before the 4th, honestly singing a patriotic hymn on the 25th seems a little early to me. After the 4th, it’s a little unclear. The Sunday after the 4th is the 11th and there’s a clear low point. But, we get a slight rise and fall again July 12th–15th. I’m not sure why that would be.</p>
<p>If we split it up by hymn, we can kind of see if any hymn is more or less popular during the “season” (<a href="#fig-by_date_by_hymn">Figure&nbsp;5</a>). The two less canonical patriotic hymns, <hymn>Battle Hymn of the Republic (#60)</hymn> and <hymn>God Of Our Fathers, Whose Almighty Hand (#78)</hymn> are about equally common throughout the season, and are, interestingly, not any more common closer to the 4th itself.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-by_date_by_hymn" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/fig-by_date_by_hymn-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption class="figure-caption">Figure&nbsp;5: Popularity of five patriotic hymns by date</figcaption>
</figure>
</div>
</div>
</div>
<p>Looking at the more prototypical 4th of July hymns, there is maybe a pattern. Unlike what we saw with the overall trend, where the highest concentration of patriotic hymns was on the 3rd and the 4th about equally, here we see that <hymn>America the Beautiful (#338)</hymn> is just slightly more common the 4th itself and then pretty quickly drops off. Meanwhile, <hymn>My Country, ’Tis of Thee (#339)</hymn> and <hymn>The Star-Spangled Banner (#340)</hymn> peak just before the 4th and have a less drastic drop-off afterwards. I’m not sure what that spike is on July 6th for <hymn>My Country, ’Tis of Thee (#339)</hymn>. Could be a fluke since I don’t have a ton of data from 2008 and 2014.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>There are three clear patriotic hymns, two additional hymns that are commonly sung around the 4th of July, and an additional half dozen or so that are uncommon generally but when they are sung it’s most likely around the 4th of July. All five of the main hymns are about equally likely as opening or closing hymns. And there’s a clear rise and fall for when you see these hymns being sung, centered around the 3rd or 4th. It will be really iinteresting to see how this changes in the next few years with the new hymns and the new hymnal!</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">Copyright 2023, Joey Stanley</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>