<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Joey Stanley">
<meta name="dcterms.date" content="2023-10-09">

<title>LDS Hymn Stats - What are the least common hymns?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-SG4E42NZ2F"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-SG4E42NZ2F', { 'anonymize_ip': true});
</script>


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="LDS Hymn Stats - What are the least common hymns?">
<meta property="og:description" content="">
<meta property="og:site-name" content="LDS Hymn Stats">
<meta name="twitter:title" content="LDS Hymn Stats - What are the least common hymns?">
<meta name="twitter:description" content="">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">LDS Hymn Stats</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../findings.html" rel="" target="">
 <span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../overview.html" rel="" target="">
 <span class="menu-text">Summarized Data</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../contribute.html" rel="" target="">
 <span class="menu-text">Contribute</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About Me</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/ldshymnstats" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/JoeyStanley/lds-hymn-stats" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../findings.xml" rel="" target=""><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<p><img src="../../images/logo.jpeg" class="img-fluid"></p>
</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#a-brief-note-about-my-calculations" id="toc-a-brief-note-about-my-calculations" class="nav-link active" data-scroll-target="#a-brief-note-about-my-calculations">A brief note about my calculations</a></li>
  <li><a href="#once-a-decade" id="toc-once-a-decade" class="nav-link" data-scroll-target="#once-a-decade">Once a decade</a></li>
  <li><a href="#once-a-generation" id="toc-once-a-generation" class="nav-link" data-scroll-target="#once-a-generation">Once a generation</a></li>
  <li><a href="#once-in-a-lifetime" id="toc-once-in-a-lifetime" class="nav-link" data-scroll-target="#once-in-a-lifetime">Once in a lifetime</a></li>
  <li><a href="#overall-frequency" id="toc-overall-frequency" class="nav-link" data-scroll-target="#overall-frequency">Overall Frequency</a></li>
  <li><a href="#concluding-thoughts" id="toc-concluding-thoughts" class="nav-link" data-scroll-target="#concluding-thoughts">Concluding thoughts</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">What are the least common hymns?</h1>
  <div class="quarto-categories">
    <div class="quarto-category">frequency</div>
    <div class="quarto-category">general</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Joey Stanley </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 9, 2023</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">October 27, 2023</p>
    </div>
  </div>
    
  </div>
  

</header>

<p><a href="../../posts/most_common">Previously</a>, I’ve posted about the most popular hymns. In this post, I’ll look at the opposite end of the spectrum: what hymns are hardly ever sung at all? Ones that, if they end up being cut from the hymnal, hardly anyone would even notice.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>I will update the results on this page from time to time as I collect more data. The first update happened just a few hours after my original post because I had received an additional 10 years of data from generous contributors. Another update happened after I got an enormous addition to my dataset from Samuel Bradshaw.</p>
</div>
</div>
<section id="a-brief-note-about-my-calculations" class="level2">
<h2 class="anchored" data-anchor-id="a-brief-note-about-my-calculations">A brief note about my calculations</h2>
<p>Let me first mention my methods for how I’m calculating how often a hymn is sung, on average, per ward. I currently have data from 18,369 sacrament meetings. A ward will meet together for sacrament meeting usually 48 times in a year (52 weeks minus two for General Conference and minus two for Stake Conference). 18,369 meetings divided by 48 meetings in a year is about 382 years’ worth of sacrament meetings—far more than any one person could attend in their lifetime. So, if there’s a hymn that’s sung in just one of those sacrament meetings, that means it’s sung, on average per ward, once every 382 years. If a hymn is sung 100 times in my dataset, it’s sung on average once every <code>18369 / 48 / 100 =</code> 3.82 years per ward.</p>
<p>Because I’m dealing with very sparse numbers in this post, the numbers may fluctuate wildly. As I <a href="../../contribute">collect more data</a>, the exact numbers jump around quite a bit when we get to the very infrequent hymns. For example, if a hymn is sung three times in my dataset, that comes out to once every 127 years. If it’s sung just twice, it’s once every 191 years. That’s a big jump for a single data point. So, you should take these numbers with a grain of salt they mostly reflect how much data I have. Instead, I’ll group them into broad categories of “once a decade,” “once a generation,” and “once in a lifetime.”</p>
<p>Please note that I have removed the men’s and women’s arrangements (hymns 309–337) from these lists because, as I’ve <a href="../../mens_womens_arrangements">already written</a>, they’re probably not really intended or appropriate for sacrament meeting.</p>
<p>So, with that in mind, let’s most on to the least common hymns.</p>
</section>
<section id="once-a-decade" class="level2">
<h2 class="anchored" data-anchor-id="once-a-decade">Once a decade</h2>
<p>Let’s start with hymns that are sung once every 10 to about 25 years or so. In other words, these are ones that were sung between about 16 to 38 times in the entire sample. In my current dataset, there are 37 hymns that fit into this category. The following table shows these hymns in order of appearance in the hymnal.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 67%">
<col style="width: 18%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Hymn</th>
<th style="text-align: right;">Every X Years</th>
<th style="text-align: right;">Times Sung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">What Was Witnessed in the Heavens? (11)</td>
<td style="text-align: right;">14.2</td>
<td style="text-align: right;">27</td>
</tr>
<tr class="even">
<td style="text-align: left;">’Twas Witnessed in the Morning Sky (12)</td>
<td style="text-align: right;">22.5</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I Saw a Mighty Angel Fly (15)</td>
<td style="text-align: right;">10.9</td>
<td style="text-align: right;">35</td>
</tr>
<tr class="even">
<td style="text-align: left;">The Voice of God Again Is Heard (18)</td>
<td style="text-align: right;">18.2</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Saints, Behold How Great Jehovah (28)</td>
<td style="text-align: right;">13.2</td>
<td style="text-align: right;">29</td>
</tr>
<tr class="even">
<td style="text-align: left;">Our Mountain Home So Dear (33)</td>
<td style="text-align: right;">14.2</td>
<td style="text-align: right;">27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The Wintry Day, Descending to Its Close (37)</td>
<td style="text-align: right;">21.3</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="even">
<td style="text-align: left;">O Saints of Zion (39)</td>
<td style="text-align: right;">12.0</td>
<td style="text-align: right;">32</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Arise, O Glorious Zion (40)</td>
<td style="text-align: right;">20.1</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hail to the Brightness of Zion’s Glad Morning! (42)</td>
<td style="text-align: right;">12.8</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Glorious Things of Thee Are Spoken (46)</td>
<td style="text-align: right;">18.2</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="even">
<td style="text-align: left;">We Will Sing of Zion (47)</td>
<td style="text-align: right;">10.1</td>
<td style="text-align: right;">38</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adam-ondi-Ahman (49)</td>
<td style="text-align: right;">12.0</td>
<td style="text-align: right;">32</td>
</tr>
<tr class="even">
<td style="text-align: left;">Come, Though Glorious Day of Promise (50)</td>
<td style="text-align: right;">19.1</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lo, the Mighty God Appearing! (55)</td>
<td style="text-align: right;">23.9</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Raise Your Voices to the Lord (61)</td>
<td style="text-align: right;">10.9</td>
<td style="text-align: right;">35</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Great King of Heaven (63)</td>
<td style="text-align: right;">16.6</td>
<td style="text-align: right;">23</td>
</tr>
<tr class="even">
<td style="text-align: left;">With Songs of Praise (71)</td>
<td style="text-align: right;">11.6</td>
<td style="text-align: right;">33</td>
</tr>
<tr class="odd">
<td style="text-align: left;">God of Our Fathers, Known of Old (80)</td>
<td style="text-align: right;">13.7</td>
<td style="text-align: right;">28</td>
</tr>
<tr class="even">
<td style="text-align: left;">From All That Dwell below the Skies (90)</td>
<td style="text-align: right;">18.2</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cast Thy Burden Upon the Lord (110)</td>
<td style="text-align: right;">10.1</td>
<td style="text-align: right;">38</td>
</tr>
<tr class="even">
<td style="text-align: left;">God Is in His Holy Temple (132)</td>
<td style="text-align: right;">22.5</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Father, This Hour Has Been One of Joy (154)</td>
<td style="text-align: right;">23.9</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Now the Day Is Over (159)</td>
<td style="text-align: right;">17.4</td>
<td style="text-align: right;">22</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lord, We Come Before Thee Now (162)</td>
<td style="text-align: right;">14.7</td>
<td style="text-align: right;">26</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hear Thou Our Hymn, O Lord (222)</td>
<td style="text-align: right;">12.0</td>
<td style="text-align: right;">32</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Father, Cheer Our Souls Tonight (231)</td>
<td style="text-align: right;">20.1</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nay, Speak No Ill (233)</td>
<td style="text-align: right;">15.3</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Should You Feel Inclined to Censure (235)</td>
<td style="text-align: right;">13.7</td>
<td style="text-align: right;">28</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lord, Accept into Thy Kingdom (236)</td>
<td style="text-align: right;">19.1</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Up, Awake, Ye Defenders of Zion (248)</td>
<td style="text-align: right;">15.9</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="even">
<td style="text-align: left;">Come, All Whose Souls Are Lighted (268)</td>
<td style="text-align: right;">23.9</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Men Are That They Might Have Joy (275)</td>
<td style="text-align: right;">20.1</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="even">
<td style="text-align: left;">Come Away to the Sunday School (276)</td>
<td style="text-align: right;">15.9</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The Glorious Gospel Light Has Shone (283)</td>
<td style="text-align: right;">18.2</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rejoice, Ye Saints of Latter Days (290)</td>
<td style="text-align: right;">16.6</td>
<td style="text-align: right;">23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">God’s Daily Care (306)</td>
<td style="text-align: right;">13.7</td>
<td style="text-align: right;">28</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>As an LDS musician basically my entire life, I can tell you that I could probably sing the melody for only a few of these: <hymn>What Was Witnessed in the Heavens? (#11)</hymn>, <hymn>I Saw a Mighty Angel Fly (#15)<hymn>, <hymn>Adam-ondi-Ahman (#49)</hymn>, <hymn>Should You Feel Inclined to Censure (#235)</hymn>. I like to think of <hymn>The Wintry Day, Descending to Its Close (37)</hymn> as being “famous for not being famous,” particularly among LDS musicians, and with its <a href="../../posts/highest_melody">high melody</a> and tenor lines, unusual chords, and potentially offensive lyrics, it’s no surprise that it’s not sung very often. Some of these hymns are ones that the Tabernacle Choir sings but that I otherwise don’t recognize. Most of the hymns in the first half the hymnal, I hardly recognize at all. Meanwhile, the ones in the second half of the hymnal are ones that I recognize only because they’re interspersed among some of the more common, upbeat hymns in the 200-range. Overall, there is nothing too surprising here: there aren’t any hymns that I feel like are more popular than they really are.</hymn></hymn></p>
</section>
<section id="once-a-generation" class="level2">
<h2 class="anchored" data-anchor-id="once-a-generation">Once a generation</h2>
<p>The next table shows ones that are sung about once every <em>generation</em> or two. I’m defining these are those that are sung, on average per ward, once every 25 to 45 years. In my data, they show up in just 9–15 sacrament meetings. There are 13 hymns in this category, which you can see in the following table.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 63%">
<col style="width: 20%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Hymn</th>
<th style="text-align: right;">Every X Years</th>
<th style="text-align: right;">Times Sung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">The Happy Day at Last Has Come (32)</td>
<td style="text-align: right;">27.3</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zion Stands with Hills Surrounded (43)</td>
<td style="text-align: right;">31.9</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Glorious Things Are Sung of Zion (48)</td>
<td style="text-align: right;">34.8</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Let Earth’s Inhabitants Rejoice (53)</td>
<td style="text-align: right;">38.3</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Behold, the Mountain of the Lord (54)</td>
<td style="text-align: right;">29.4</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">We’re Not Ashamed to Own Our Lord (57)</td>
<td style="text-align: right;">25.5</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Praise Ye the Lord (74)</td>
<td style="text-align: right;">38.3</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Great Is the Lord (77)</td>
<td style="text-align: right;">25.5</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">With All the Power of Heart and Tongue (79)</td>
<td style="text-align: right;">34.8</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="even">
<td style="text-align: left;">As the Shadows Fall (168)</td>
<td style="text-align: right;">34.8</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jesus, Mighty King in Zion (234)</td>
<td style="text-align: right;">25.5</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="even">
<td style="text-align: left;">Like Ten Thousand Legions Marching (253)</td>
<td style="text-align: right;">42.5</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Go, Ye Messengers of Glory (262)</td>
<td style="text-align: right;">42.5</td>
<td style="text-align: right;">9</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Among this set of hymns, I only recognize one, <hymn>As the Shadows Fall (168)</hymn>, and not because I’ve sung it in church, but because it’s one of <a href="../../posts/key_signatures">only two hymns in the key of D♭</a>. As far as the rest go, I don’t even recognize their titles.</p>
<p>The wild thing is that the current hymnal was published in 1985, which is 38 years ago. If these numbers are accurate, it means that these hymns might have been sung maybe once or twice in the entire lifetime of the hymnal!</p>
</section>
<section id="once-in-a-lifetime" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="once-in-a-lifetime">Once in a lifetime</h2>
<p>Finally, we get to the seventeen hymns that are sung at most eight times in the 18,369 sacrament meetings I have data from. Again, keep in mind that because I’m dealing with such sparse data, saying something is sung once every 382 years is very approximate and just reflects how much data I have total. Instead, you should just think of these hymns as being sung once-in-a-lifetime.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Hymn</th>
<th style="text-align: left;">Every X Years</th>
<th style="text-align: right;">Times Sung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">What Glorious Scenes Mine Eyes Behold (16)</td>
<td style="text-align: left;">63.8</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sons of Michael, He Approaches (51)</td>
<td style="text-align: left;">382.7</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Softly Beams the Sacred Dawning (56)</td>
<td style="text-align: left;">76.5</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Great God, Attend While Zion Sings (88)</td>
<td style="text-align: left;">54.7</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ye Simple Souls Who Stray (118)</td>
<td style="text-align: left;">76.5</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lean on My Ample Arm (120)</td>
<td style="text-align: left;">47.8</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I’m a Pilgrim, I’m a Stranger (121)</td>
<td style="text-align: left;">54.7</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">How Long, O Lord Most Holy and True? (126)</td>
<td style="text-align: left;">47.8</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Softly Now the Light of Day (160)</td>
<td style="text-align: left;">47.8</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Great God, to Thee My Evening Song (164)</td>
<td style="text-align: left;">63.8</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Come, Let Us Sing an Evening Hymn (167)</td>
<td style="text-align: left;">47.8</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Behold Thy Sons and Daughters, Lord (238)</td>
<td style="text-align: left;">54.7</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">This House We Dedicate to Thee (245)</td>
<td style="text-align: left;">95.7</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rejoice! A Glorious Sound Is Heard (257)</td>
<td style="text-align: left;">54.7</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Thy Servants Are Prepared (261)</td>
<td style="text-align: left;">47.8</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">We Meet Again in Sabbath School (282)</td>
<td style="text-align: left;">47.8</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">God Save the King (341)</td>
<td style="text-align: left;">191.3</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>If the previous category of hymns (the “once in a generation” ones) were rare, these are even rarer. Another way of thinking about these is that in the lifetime of a physical copy of a hymnal, there is a decent chance that most of these nine hymns were <em>never</em> sung.</p>
<div class="page-columns page-full"><p>I recognize two of these hymns because they stand out in interesting ways. First, is <hymn>Lean on My Ample Arm (120)</hymn> which is my favorite hymn. There’s also <hymn>Softly Now the Light of Day (160)</hymn> which, at only two lines and one verse, is tied with the once-every-six-years <hymn>Praise God, from Whom All Blessings Flow (242)</hymn> for the shortest hymn in the hymnal..</p><div class="no-row-height column-margin column-container"><span class="">If you want to get really technical, Hymn 242 is shorter because its suggested tempo marking includes slower tempos.</span></div></div>
<p>Others in this list can be explained a little bit.</p>
<ul>
<li><p>Here we get <a href="../../posts/key_signatures">the other hymn in D♭</a>, <hymn>Softly Beams the Sacred Dawning (56)</hymn>.</p></li>
<li><p><hymn>We Meet Again in Sabbath School (282)</hymn> makes sense for being on this list because it’s likely intended to be an opening hymn for Sunday School, and not sacrament meeting. Although, we don’t start Sunday School with hymns anymore, so it’s likely not getting any currency anymore.</p></li>
<li><p>The hymn <hymn>Come, Let Us Sing an Evening Hymn (167)</hymn> makes sense since most wards meet in the morning.</p></li>
<li><p>It’s also not surprising that <hymn>God Save the King (341)</hymn> is hardly sung in my sample, partially because I don’t have a lot of data from the UK and the reigning monarch the entire time was a queen rather than a king.</p></li>
<li><p>Finally, it seems like <hymn>This House We Dedicate to Thee (#245)</hymn> is intended for a building dedication which probably not very many people actually get to attend in their lifetimes. It’s a perfectly good hymn and very appropriate for the occasion—but regular sacrament meeting is not such an occasion.</p></li>
</ul>
<div class="no-row-height column-margin column-container"><span class="">When I was a teenager, we actually sang <hymn>God Save the King (#341)</hymn> in Priesthood Opening Exercises, back when they had those. We did it becauase one of the young women from the ward was sitting in because she needed to make an announcement, so the Bishop asked her to give the prayer, because, how often do you see a young woman give the opening prayer in a Priesthood meeting? So, while we’re seeing things we’ve never seen before, we sang <hymn>God Save the King (#341)</hymn>.</span></div><p>It is interesting to note that, with a large enough sample and if you ignore the men’s and women’s arrangements in the back, I was able to find evidence of every hymn being sung at least once in some meeting somewhere.</p>
</section>
<section id="overall-frequency" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="overall-frequency">Overall Frequency</h2>
<p>To me, it is wild to think that these 17 hymns (plus many of the men’s and women’s arrangements) have been printed in tens of thousands of hymnals for the past nearly 40 years and have hardly ever been used by anyone. On the plus side, these lists are somewhat small, especially the list of hymns never sung at all. It appears to be the case then that pretty much every hymn is sung at least a little bit. So, inflated claims along the lines of “there are 100 hymns that literally no one sings” simply aren’t accurate. They’re not common, but they are sung.</p>
<p>In fact, if we take all 67 hymns that I’ve listed on this page, and count up how many times they were sung, it comes out to 1,180 times in this sample, which is 1.85% of all the data. That means you might sing one of these 67 hymns once every four months, or about as often as <a href="../../posts/most_common"><hymn>I Stand All Amazed (193)</hymn></a>. Another way of thinking about it is that we could cut these 67 hymns, and it would affect about one meeting every four months.</p>
<div class="page-columns page-full"><p>Perhaps a better way of looking at this is to think about how many wards sing a given hymn around the world. There are around 31,330 wards and branches across the world. Let’s say that the 18,369 meetings I have data are a representative sample with one ward contributing data all in the same week. That would be 58.6% of the congregations around the whole world. If one of them sings something like <hymn>Sons of Michael, He Approaches (#51)</hymn>, we might therefore assume that perhaps maybe one other congregation around the world will sing that hymn in a given week. For comparison, if we apply the same logic, <hymn>I Stand All Amazed (#193)</hymn> would be sung in 1,755 different congregations every week.</p><div class="no-row-height column-margin column-container"><span class="">See more facts and figures published by the church <a href="https://newsroom.churchofjesuschrist.org/facts-and-statistics/country/united-states">here</a>.</span></div></div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caveats
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You should take that claim about how many wards around the world sing these hymns with a monster grain of salt for at least the following reasons:</p>
<ol type="1">
<li><p>The wards I have data from are not representative of units across the world. Roughly 85% of my data comes from the US, for example, while less than half the congregations in the world come from the US.</p></li>
<li><p>We can’t assume the 18,369 meetings are independent of each other because most wards contributed data from more than one sacrament meeting. So we can’t interpret them as coming from 18,369 independent wards in the same week.</p></li>
<li><p>As we’ll see in later posts, holidays matter, and the likelihood of singing any one hymn goes up and down depending on things like holidays, Fast Sundays, and proximity to <a href="../../posts/general_conference.html">General Conference</a>. So the odds of singing these unusual hymns is basically zero the week before Christmas, but slightly higher in a random week in September or something.</p></li>
<li><p>Also, the type of music coordinators that keep spreadsheets are likely the ones who try to diversify the hymns they sing. There are likely many wards who do not have spreadsheets and may sing from a more limited selection throughout the year.</p></li>
</ol>
<p>I wanted to point out these caveats, but it’s still interesting to think about how many times these hymns are sung around the world on a given Sunday.</p>
</div>
</div>
</div>
</section>
<section id="concluding-thoughts" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="concluding-thoughts">Concluding thoughts</h2>
<p>In this blog post, I took a closer look at hymns that are sung at most once a decade. Many of them were sung less often that that, if they were sung at all.</p>
<p>But <em>should</em> we cut these hymns? Unless there are issues with the text, message, or doctrine, I don’t see any reason why we should remove hymns <em>per se</em>. In fact, some hymns, like <hymn>We Meet Again in Sabbath School (#282)</hymn> or <hymn>This House We Dedicate to Thee (#245)</hymn> are/were quite appropriate in very specific, albeit infrequent, circumstances. So, should they be printed in tens of thousands of hymnals? In my opinion, probably not.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Recommendation for the next hymnal
</div>
</div>
<div class="callout-body-container callout-body">
<p>Put these special hymns into an online supplement to the hymnal, like <a href="../../posts/mens_womens_arrangements.html#my-recommendations-for-the-next-hymnal">what I recommend for the men’s and women’s arrangements</a>. Make it clear that these are approved for use in the church and part of the “canon” but are simply not printed for practical reasons.</p>
<p>As for the special hymns that are useful for certain occasions, set them aside in a section called “special occasions” or something that would catch people’s attention. We don’t want them to be overlooked when those special occasions do arise. It would be a shame to lose these hymns simply because the occasions they are written for don’t happen very often.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Recommendation to music coordinators
</div>
</div>
<div class="callout-body-container callout-body">
<p>It is unlikely that many people in your ward will be familiar with more than a few hymns listed on this page. If you want to be adventurous and try a really uncommon hymm, these are the ones to choose from. But, it might be good to help the ward out a little bit by having the ward choir sing it first, having the organist play it for prelude a few weeks prior, having the organist play the entire hymn as an introduction, and having the organist use play the melody on the swell (or use a melody coupler) with a reed stop pulled to make it easier to hear.</p>
<p>Regardless of whether you use these hymns, you should get familiar with these techniques for introducing hymns to ward members because we’ll all likely need to start using them when we get the new hymnal anyway.</p>
</div>
</div>
<div class="no-row-height column-margin column-container"><span class="callout-margin-content">Funny story. Someone contributed a couple years’ worth of data from their ward and I mentioned that they sang three of the most unusual hymns in the span of two weeks. The sister wrote back saying the music coordinator was released right after that and she was called with a special request from her bishop to sing songs people were familiar with. So, if you go too overboard, it might cost you your calling!</span></div><p>If you have sung one of these 67 hymns recently in your ward, that’s pretty cool because few people can sasy they have!</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">Copyright 2023, Joey Stanley</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>