---
title: "Logo"
author: "Joey Stanley"
date: "2023-09-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

It'd be cool to develop a logo that is the tabernacle organ but as a barplot.

```{r}
library(tidyverse)
```

```{r, fig.height = 1, fig.width = 1.5}
pipe_heights <- c(13, 10.25, 10.15, 10, 10, 
                  11, 10, 10, 10.15, 10.25, 
                  15, 10.25,
                  19, 20, 19,
                  13, 13, 12) - 4
tibble(y_position = c(pipe_heights, 12, rev(pipe_heights))) %>%
    rowid_to_column("x_position") %>%
    ggplot(aes(x_position, y_position)) + 
    geom_col(width = 0.75, fill = "gray50") + 
    geom_point(aes(size = y_position)) + 
    geom_path(aes(y = y_position/4), color = "#4477aa", linewidth = 0.5) + 
    scale_y_continuous(limits = c(0, 18)) + 
    scale_size_continuous(range = c(0.25, 1)) + 
    theme_minimal() + 
    theme(axis.title = element_blank(),
          axis.text  = element_blank(),
          axis.ticks = element_blank(),
          axis.line = element_line(color = "gray20", linewidth = 0.5),
          legend.position = "none")
ggsave("logo.jpeg", height = 1, width = 1.5)
```


