---
title: "Are these hymns appropriate for sacrament meeting?"
author: "Joey Stanley"
date: 2025-03-03
date-modified: last-modified
categories:
  - general
  - new hymns
draft: TRUE
---

Yes, of course they are. If Christ approves, then I approve, and who am I to say otherwise?

## Playing piano acommpaniments on the organ

Some people have complained that the new hymns are arranged specifically for piano and that playing them as-is on the organ doesn't sound good. I can see where they are coming from, but ultimately that is a matter of personal taste. I see three rather obvious solutions to solve this problem:

1. A good organist should be able to adapt simple arrangements like these on the fly to be more suitable for organ accompaniment. 

1. Just go play the piano.

1. Church members need to expand their idea of what is considered suitable music for sacrament meeting. 

## They simply can't be played on the organ

You need to understand that the organ is capable of more than SATB arrangements.



## But Brother So-and-So has a low voice! What is he supposed to sing then??

Do you honestly think that every single member of your ward is singing the part suitable for their voice? Absolutely not. There are tons of people without much musical training or ability that get along just fine with singing the melody in whatever range they feel comfortable with. If that means they're singing an octave lower than they """should""" be singing, that's fine. When confronted with a new hymn without parts, they're keep doing what they have been doing and will sing that melody in a way that works best for them. 

If someone has musical ability and struggles with the range of the melody, I'm pretty sure they'll find a way. They'll make up a harmony line based on the accompaniment or maybe sing down an octave. I don't think people will stop singing simply because there are no harmony lines. 


## "Songs" vs. "Hymns"

As [a linguist by day](joeystanley.com), I can tell you that words are powerful. And unfortunately, I'm seeing a subtle shift in how the words *song* and *hymn* are used. I'm noticing that people are using the word *song* to refer to musical pieces that were originally published with a melody line and piano accompaniment, while *hymn* is for musical pieces that are traditionally sung in SATB. With this distinction, "I Will Walk with Jesus" would be a *song* while "Come, Thou Fount of Every Blessing" would be a *hymn*. 

This distinction might stem from the fact that for the past couple decades, the two main books of music we've been using are called "Hymns" and "Children's Songbook." The distinction is reinforced by the fact that the table of contents to "Hymns" has section called "Children's Songs" that contains several pieces that, by the above definition, would be considered "songs." 

I'm rather opposed to this distinction. For one, it doesn't hold up to scrutiny. Are "Because I Have Been Given Much", "Come, Rejoice", "As Zion's Youth in Latter Days", "Families Can Be Together Forever", and "I Know My Father Lives" not hymns? Do "Ye Simple Souls Who Stray", "I Know That My Redeemer Lives", "I Stand All Amazed", "Carry On", "Called to Serve", and "Behold! A Royal Army" switch between being hymns and songs partway through? Are verses 1, 2, and 5 of "For All the Saints" songs, while verses 3 and 4 are hymns? What makes "The Light Divine" and "In Our Lovely Deseret" any more of a hymn than "Families Can Be Together Forever", other than they happen to be arranged in this book in SATB? What makes "Beautiful Savior", which is essentially written in SATB in the Children's Songbook, a "song" and not a "hymn"? Even worse are the occasional comments that imply that African American spirituals are not "hymns." Specifically, I'm talking about "This Little Light of Mine". 

Perhaps at a deeper level, the use of *songs* for something like "I Will Walk with Jesus" seems rather pejorative. Are musical pieces intended for children not "worthy" of being called *hymns*? 

